Add yaml header check wip
geotribu/cli pull request #184
Opened 2024-03-17 20:29 UTC by gounux

#178

2024-04-17 18:31 UTC, gounux commented
cc @Guts 

> L'idéal serait que la commande sorte un texte en markdown et qu'on soit en mesure de la faire tourner dans la CI. Mais bon sur ce point, il faudrait d'abord résoudre l'ambiguité sur quel contenu est à publier et donc à checker.

En l'état la commande prend en paramètre un fichier et vérifie quelques trucs par rapport à l'entête. On part sur vérifier tous les contenus dans la CI ? Compliqué alors de gérer les dates ?

> À noter qu'il y a déjà des amorces dans le code avec python-frontmatter mais que c'est éparse ou à refaire. D'ailleurs, il serait peut-être plus intéressant de lire les fichiers Markdown avec Mkdocs pour utiliser le même outil.

Actuellement il n'y a pas d'outils externes utilisés, si tu as des idées je suis preneur

2024-04-25 19:41 UTC, Guts commented on geotribu_cli/content/json_feed.py
C'est à mettre dans une autre branche non ?

2024-04-25 19:43 UTC, Guts commented on geotribu_cli/content/header_check.py
> +            os.remove(image_file_name)
Utiliser https://github.com/geotribu/cli/blob/274e435e7fa70b4358341fa9f4ce3f0eed1c8219/geotribu_cli/utils/check_image_size.py#L89 ?

2024-04-25 19:43 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return jfc.get_tags(should_sort=True)
Ah ok j'ai pigé pourquoi tu utilises le JSON Feed !

Il y a plus complet : https://geotribu.fr/tags.json

2024-04-25 19:44 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    if not os.path.exists(content_path):
Utiliser https://github.com/geotribu/cli/blob/a88eacc3420b8a463a29af0a2e6387c6016167b4/geotribu_cli/utils/check_path.py

2024-04-26 07:21 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return jfc.get_tags(should_sort=True)
Ah ouais sympa :+1:

2024-05-23 09:17 UTC, gounux commented on geotribu_cli/content/header_check.py
> +            os.remove(image_file_name)
Il y a une nouvelle fonction `utils` qui récupère les dimensions de l'image à partir de l'URL

2024-05-27 16:33 UTC, Guts requested changes
Le package tiers unicode est overkill pour le besoin et on a déjà un gros paquet de dépendances à trainer :/.

Le check de vérification de l'ordre alphabétique des tags semble ne pas fonctionner :

```python
geotribu check ../website/content/articles/2024/2024-03-18_crowdscourcing_avec_cocarto.md 
2024-05-27 18:31:31||ERROR||header_check||run||218||Les tags ne sont pas triés par ordre alphabétique : ['cocarto', 'contribution', 'collecte', 'collecte terrain', 'smartphone']
```

Allez zou, après ça, on merge, on package et on teste en conditions réelles

2024-05-27 16:33 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    p = os.path.join(folder, f"{unidecode(formatted.lower())}.md")
C'est overkill non pour gérer l'encodage vu que tous les fichiers sont supposément en UTF-8 ?

```suggestion
    p = os.path.join(folder, f"{unidecode(formatted.lower())}.md")
```

2024-05-27 16:33 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    formatted = author.translate(str.maketrans({"'": "", " ": "-"}))
Oh je connaissais pas la méthode translate !

2024-05-27 16:44 UTC, Guts requested changes
Quelques suggestions pour utiliser pathlib pour être plus cohérent avec le reste de la base de code

2024-05-27 16:44 UTC, Guts commented on geotribu_cli/content/header_check.py
> +        type=str,
```suggestion
        type=Path,
```

2024-05-27 16:44 UTC, Guts commented on geotribu_cli/content/header_check.py
> +from geotribu_cli.utils.check_path import check_path_exists
```suggestion
from geotribu_cli.utils.check_path import check_path
```

2024-05-27 16:44 UTC, Guts commented on geotribu_cli/content/header_check.py
> +            content = frontmatter.load(file)
```suggestion
    logger.debug(f"Running {args.command} with {args}")
    content_paths: list[Path] = args.content_path

    for content_path in content_paths:
        logger.info(f"Checking header of {content_path}")
        check_path(
            input_path=content_path,
            must_be_a_file=True,
            must_be_a_folder=False,
            must_be_readable=True,
            raise_error=True,
        )


        with content_path.open(mode="r", encoding="UTF-8") as file:
            content = frontmatter.load(file)
```

2024-05-27 19:45 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    p = os.path.join(folder, f"{unidecode(formatted.lower())}.md")
C'est surtout pour remplacer les accents, du style `ë` -> `e` ...etc

2024-05-27 19:56 UTC, gounux commented
> Le check de vérification de l'ordre alphabétique des tags semble ne pas fonctionner :
> 
> ```python
> geotribu check ../website/content/articles/2024/2024-03-18_crowdscourcing_avec_cocarto.md 
> 2024-05-27 18:31:31||ERROR||header_check||run||218||Les tags ne sont pas triés par ordre alphabétique : ['cocarto', 'contribution', 'collecte', 'collecte terrain', 'smartphone']
> ```

En même temps ça ne me semble pas trié par ordre alphabétique..

2024-05-27 20:13 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    p = os.path.join(folder, f"{unidecode(formatted.lower())}.md")
L'objectif c'est d'avoir le nom du fichier auteur c'est ça ?
Si oui, alors autant utiliser le slugger qui est utilisé dans le hook du site qui gère les bloc auteurs : https://github.com/geotribu/website/blob/9fc8acade6d197322df39d42f11b63dfa4da2ea5/hooks/mkdocs/G006_authors_block.py#L15

2024-05-28 07:43 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    p = os.path.join(folder, f"{unidecode(formatted.lower())}.md")
Bien vu !

2024-05-28 08:50 UTC, Guts approved these changes

2024-05-28 09:48 UTC, merged