Remove license from mandatory keywords
geotribu/cli pull request #215
Opened 2024-06-23 07:56 UTC by gounux

2024-06-23 13:58 UTC, Guts approved these changes
J'ai pas regardé mais est-ce que tu check que la valeur correspond à l'une des licences  disponibles ?

2024-06-24 09:02 UTC, Guts requested changes

2024-06-24 09:02 UTC, Guts commented on geotribu_cli/content/header_check.py
> +AVAILABLE_LICENSES = ["default", "cc4_by-nc-sa", "cc4_by-sa", "beerware"]
Un enum plutôt ?

2024-06-24 09:02 UTC, Guts commented on geotribu_cli/content/header_check.py
> +def check_license(license: str) -> bool:
Ajouter le check value dans l'enum

2024-06-24 09:02 UTC, Guts commented on geotribu_cli/content/header_check.py
> +AVAILABLE_LICENSES = ["default", "cc4_by-nc-sa", "cc4_by-sa", "beerware"]
Ou les lister depuis le dossier ?

2024-07-02 12:17 UTC, Guts commented
@gounux je te laisse la main ;)

2024-07-02 12:34 UTC, gounux commented
@Guts tu peux merger comme un sagouin (coin coin !) ? Flemme de relancer les tests Win qui plantent :D

2024-07-02 12:34 UTC, merged