Fix unnecessary pillow import by using image size from CDN endpoint
geotribu/cli pull request #218
Opened 2024-06-24 17:45 UTC by gounux

2024-06-24 19:57 UTC, Guts requested changes

2024-06-24 19:57 UTC, Guts commented on geotribu_cli/content/header_check.py
> +
déjà dans les default settings

2024-06-24 19:57 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
Pas acceptable de faire ça vu la taille du fichier.

Le fichier est peut-être déjà téléchargé localement si search-images a déjà été utilisé avant. Et si ça n'est pas le cas, autant télécharger le fichier localement justement puisqu'il peut être utilisé par d'autres outils.

Par ailleurs, le lru cache est scopé à l'exécution donc peu de chances qu'il aie un réel impact ici. À la limite, autant utiliser un truc comme https://pypi.org/project/CacheControl/ ou requests-cache ou autre

2024-06-25 06:56 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
Je me demande si on n'est pas en train de sur-ingénieurer une question qu'on ne s'est pas vraiment posée (enfin je parle en ce qui me concerne) : concernant l'image de l'article, qu'est-ce qui nous intéresse ? Une dimension à ne pas dépasser ? Où est-ce que l'image a-t-elle vocation à s'insérer ? Ou est-ce le poids qui nous intéresse afin d'alléger les contenus ?

2024-06-25 07:03 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
En effet, on aurait dû commencer par se rappeler pourquoi on fait ça. L'idée est donc de vérifier la conformité des différents éléments de la structure d'un contenu.

La référence c'est le guide de contribution. S'il n'est pas à jour ou lacunaire, on commence par l'aligner sur le code sous-jacent.

Pour les images, il y a donc une contrainte de format (png ou jpeg), de ratio de dimensions et de poids.

2024-06-25 07:25 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
Entendu @Guts, alors on peut partir sur 2 checks : un sur le poids (max 1MO si c'est ok) et un sur la dimension max (800px)

Sachant que là c'est uniquement le check de l'image dans l'entête markdown, ça pourra aussi être l'occasion plus tard de vérifier la conformité de toutes les images présentes dans un article

2024-06-25 07:35 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
> un sur le poids (max 1MO si c'est ok) et un sur la dimension max (800px)

Partons là-dessus. Pour la dimension, c'est largeur et hauteur max ET ratio. Sinon c'est moche sur la page d'accueil et ça fait péter aussi la mise en page de Mailchimp.

Il faut aussi vérifier que le format est l'un de ceux compatibles avec le RSS. C'est impératif vu que c'est le point d'entré vers de nombreux canaux de diffusion (qtribu, newsletter...).


> Sachant que là c'est uniquement le check de l'image dans l'entête markdown, ça pourra aussi être l'occasion plus tard de vérifier la conformité de toutes les images présentes dans un article

+1000 ! Un sujet à la fois. L'en-tête est quasiment le point le plus important ou plutôt celui où il y a le plus de friction vu que c'est orienté dév/tekoss (clés/valeurs, syntaxe YAML...).

2024-07-02 19:04 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
À celui de la page d'accueil. cf https://github.com/geotribu/website/pull/1077#issuecomment-2202566632

2024-07-02 19:54 UTC, Guts commented
@gounux je me suis permis merger main pour checker que mon fix des flaky tests fonctionne :crossed_fingers:

2024-07-03 07:01 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
Un ratio largeur / hauteur entre 1.45 et 1.55 ?

2024-07-03 07:10 UTC, Guts commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
Aucune idée, je comptais sur toi pour faire les mathématiques 😁

2024-07-03 07:27 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
:D oui mais toi tu es un esthète, et tu possèdes des talents de design graphique que j'aimerais bien avoir ! Par conséquent ton avis m'importe

2024-07-03 07:31 UTC, gounux commented on geotribu_cli/content/header_check.py
> +    return image_req.json()["images"]
C'est du 1.5 sur la page d'accueil pour info

2024-07-03 07:55 UTC, gounux commented
kikou @Guts, à mes yeux c'est prêt pour review, avec les derniers ajouts:

- vérification de la taille de l'image de l'en-tête (max : 800px, configurable en argument du cli)
- vérification du ratio de l'image de l'en-tête (entre 1.45 et 1.55, configurable en argument du cli)
- vérification de l'extension de l'image de l'en-tête (doit être parmi les valeurs de la variable `defaults_settings.images_header_extensions` soit `".png", ".jpg", ".jpeg"`)

2024-07-03 07:59 UTC, gounux commented
à l'avenir ça mériterait un petit coup de refactoring, SonarLint me souffle dans l'oreillette que la complexité de la fonction `run` est de 80 vs les 15 max recommandés :D

2024-07-03 08:06 UTC, Guts approved these changes
Allez, go, on verra pour itérer plus tard pour le refacto/optim surtout que tu es allergique aux docstrings xD !

2024-07-03 08:07 UTC, gounux commented
> Allez, go, on verra pour itérer plus tard pour le refacto/optim surtout que tu es allergique aux docstrings xD !

Je me soigne ...

2024-07-03 08:07 UTC, merged

2024-07-03 08:08 UTC, Guts commented
> > Allez, go, on verra pour itérer plus tard pour le refacto/optim surtout que tu es allergique aux docstrings xD !
> 
> Je me soigne ...

Si t'es sur VS Code, y'a l'extension autodocstring qui fait la structure automatique avec la config qui va bien dans le projet.